[versions]
# Compose
compose = "1.11.1"
composablesUi = "0.1.0"
composeUnstyled = "2.7.0"
iconsLucide = "1.0.0"

# Kotlin
kotlin = "2.4.0"
spotless = "7.2.1"

# Android
agp = "9.0.0"
android-compileSdk = "37"
android-minSdk = "23"
android-targetSdk = "36"
activityCompose = "1.13.0"


[libraries]
composables-icons-lucide = { group = "com.composables", name = "icons-lucide", version.ref = "iconsLucide" }
composables-ui = { group = "com.composables", name = "ui", version.ref = "composablesUi" }
compose-unstyled = { group = "com.composables", name = "composeunstyled", version.ref = "composeUnstyled" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
